package carrace;

import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;

public class CarRaceGUI extends javax.swing.JFrame {

    DefaultListModel<String> list1 = new DefaultListModel();
    DefaultListModel<String> list2 = new DefaultListModel();
    int[] arrayRangeCars = new int[10];
    String[] arrayTrueFalse = new String[10];
    Vehicle[] garage = new Vehicle[10];
    int mpg;
    int fuelcap;
    int passangers;
    int num = 0;
    int km = 0;

    public void createCar() {
        if(num<=9){
            fuelcap = Integer.parseInt(txtfFuelcapInput.getText());
            mpg = Integer.parseInt(txtfMpgInput.getText());
            passangers = Integer.parseInt(txtfInputPassangers.getText());
            km = Integer.parseInt(txtfDistanceInput.getText());
            lblOutCountCars.setText("(" + (num + 1) + "/10)");
            Vehicle car = new Vehicle(fuelcap, mpg, passangers);
            garage[num] = car;
            arrayRangeCars[num] = car.getFuelcap() * car.getMpg();
            list1.addElement(arrayRangeCars[num] + "");
            if (garage[num].getInfo(km)) {
                arrayTrueFalse[num] = "Проедет";
            } else {
                arrayTrueFalse[num] = "Не проедет";
            }
            list2.addElement(arrayTrueFalse[num]);
            listTrueOrFalse.setModel(list2);

            listCarRange.setModel(list1);
            num++;
        } else {
            
        }
        
//        if (txtfDistanceInput.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(rootPane, "Строка пуста!");
//        } else {
//            int i = 0;
//            garage[i] = car;
//            range = car.getMpg() * car.getFuelcap();
//            list1.addElement(range + "");
//
//            listCarRange.setModel(list1);
//            i++;

//            } else {
//                JOptionPane.showMessageDialog(rootPane, "Не больше 10 машин");
//            }
//            boolean boolCar1 = car1.getInfo(Integer.valueOf(txtfDistanceInput.getText()));
//            lblCarText.setText("Машина номер");
//            if (boolCar1) {
//                lblCarText.setText(lblCarText.getText() + " 1 проедет");
//            } else {
//                lblCarText.setText(lblCarText.getText() + " 1 не проедет");
//            }
//
//            boolean boolCar2 = car2.getInfo(Integer.valueOf(txtfDistanceInput.getText()));
//            jLabel2.setText("Машина номер");
//            if (boolCar2) {
//                jLabel2.setText(jLabel2.getText() + " 2 проедет");
//            } else {
//                jLabel2.setText(jLabel2.getText() + " 2 не проедет");
//            }
//
//            boolean boolCar3 = car3.getInfo(Integer.valueOf(txtfDistanceInput.getText()));
//            jLabel3.setText("Машина номер");
//            if (boolCar3) {
//                jLabel3.setText(jLabel3.getText() + " 3 проедет");
//            } else {
//                jLabel3.setText(jLabel3.getText() + " 3 не проедет");
//            }
//        }
//        if(car1.getInfo(km)==false){
//            jLabel1.setText("Не проедет");
//        } else {
//            jLabel1.setText("Проедет");
//        }
//        if(car2.getInfo(km)==false){
//            jLabel2.setText("Не проедет");
//        } else {
//            jLabel2.setText("Проедет");
//        }
//        if(car3.getInfo(km)==false){
//            jLabel3.setText("Не проедет");
//        } else {
//            jLabel3.setText("Проедет");
//        }
    }

    public void Random(){
        for (int i = 0; i <= 9; i++) {
            mpg = (int) (Math.random()*50);
            fuelcap = (int) (Math.random()*50);
            passangers = (int) (Math.random()*50);
            Vehicle car = new Vehicle(fuelcap, mpg, passangers);
            garage[num] = car;
            arrayRangeCars[num] = car.getFuelcap() * car.getMpg();
            list1.addElement(arrayRangeCars[num] + "");
            if (garage[num].getInfo(km)) {
                arrayTrueFalse[num] = "Проедет";
            } else {
                arrayTrueFalse[num] = "Не проедет";
            }
            list2.addElement(arrayTrueFalse[num]);
            listTrueOrFalse.setModel(list2);

            listCarRange.setModel(list1);
            num++;
        }
        
    }
    
    public CarRaceGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStart = new javax.swing.JButton();
        txtfDistanceInput = new javax.swing.JTextField();
        btnAddCar = new javax.swing.JButton();
        txtfMpgInput = new javax.swing.JTextField();
        txtfFuelcapInput = new javax.swing.JTextField();
        txtfInputPassangers = new javax.swing.JTextField();
        lblCarText = new javax.swing.JLabel();
        btnRandomCars = new javax.swing.JButton();
        scrollp3 = new javax.swing.JScrollPane();
        listCarRange = new javax.swing.JList<>();
        scrollp4 = new javax.swing.JScrollPane();
        listTrueOrFalse = new javax.swing.JList<>();
        lblTextList1 = new javax.swing.JLabel();
        lblTextList2 = new javax.swing.JLabel();
        lblOutCountCars = new javax.swing.JLabel();
        lblMpgText = new javax.swing.JLabel();
        lblFuelcapText = new javax.swing.JLabel();
        lblPassangerText = new javax.swing.JLabel();
        lblDistanceText = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        miAbout = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        txtfDistanceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDistanceInputActionPerformed(evt);
            }
        });

        btnAddCar.setText("Добавить");
        btnAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarActionPerformed(evt);
            }
        });

        txtfMpgInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfMpgInputActionPerformed(evt);
            }
        });

        lblCarText.setText("Машина");

        btnRandomCars.setText("Random");
        btnRandomCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomCarsActionPerformed(evt);
            }
        });

        scrollp3.setViewportView(listCarRange);

        scrollp4.setViewportView(listTrueOrFalse);

        lblTextList1.setText("<html>Расстояние,<p> проехавшей <p>машины</html>");

        lblTextList2.setText("Проедет ли");

        lblOutCountCars.setText("(0/10)");

        lblMpgText.setText("Расход");

        lblFuelcapText.setText("Емкость бака");

        lblPassangerText.setText("Пассажиры");

        lblDistanceText.setText("Расстояние");

        menu1.setText("File");

        miAbout.setText("Разработчик");
        miAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutActionPerformed(evt);
            }
        });
        menu1.add(miAbout);

        MenuBar.add(menu1);

        menu2.setText("Edit");
        MenuBar.add(menu2);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblFuelcapText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfFuelcapInput, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRandomCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCarText)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblOutCountCars))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lblMpgText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfMpgInput, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPassangerText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfInputPassangers, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 98, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblDistanceText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtfDistanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnStart))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollp3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollp4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTextList2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTextList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTextList2)
                                .addGap(21, 21, 21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollp3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollp4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCarText)
                        .addGap(2, 2, 2)
                        .addComponent(lblOutCountCars)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfMpgInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMpgText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfFuelcapInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFuelcapText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfInputPassangers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassangerText))
                        .addGap(36, 36, 36)
                        .addComponent(btnAddCar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRandomCars)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(txtfDistanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDistanceText))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

    }//GEN-LAST:event_btnStartActionPerformed

    private void txtfDistanceInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDistanceInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDistanceInputActionPerformed

    private void btnAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarActionPerformed
        createCar();
    }//GEN-LAST:event_btnAddCarActionPerformed

    private void txtfMpgInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfMpgInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfMpgInputActionPerformed

    private void btnRandomCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomCarsActionPerformed
        Random();
    }//GEN-LAST:event_btnRandomCarsActionPerformed

    private void miAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Выполнил Калистратов Артём Дмитриевич 21-ИС-1");
    }//GEN-LAST:event_miAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarRaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarRaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarRaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRaceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarRaceGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton btnAddCar;
    private javax.swing.JButton btnRandomCars;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblCarText;
    private javax.swing.JLabel lblDistanceText;
    private javax.swing.JLabel lblFuelcapText;
    private javax.swing.JLabel lblMpgText;
    private javax.swing.JLabel lblOutCountCars;
    private javax.swing.JLabel lblPassangerText;
    private javax.swing.JLabel lblTextList1;
    private javax.swing.JLabel lblTextList2;
    private javax.swing.JList<String> listCarRange;
    private javax.swing.JList<String> listTrueOrFalse;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenu menu2;
    private javax.swing.JMenuItem miAbout;
    private javax.swing.JScrollPane scrollp3;
    private javax.swing.JScrollPane scrollp4;
    private javax.swing.JTextField txtfDistanceInput;
    private javax.swing.JTextField txtfFuelcapInput;
    private javax.swing.JTextField txtfInputPassangers;
    private javax.swing.JTextField txtfMpgInput;
    // End of variables declaration//GEN-END:variables
}
